- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Tecprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    #- debug: 
    #    var: vpcout

    - name: Create Tecprofile Public Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ public_subnet1_cidr }}"
        az: "{{ zone1 }}"
        region: "{{ region }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_public_subnet1
      register: public_subnet1_out

    - name: Create Tecprofile Public Subnet 2 in Zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ public_subnet2_cidr }}"
        az: "{{ zone2 }}"
        region: "{{ region }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_public_subnet2
      register: public_subnet2_out

    - name: Create Tecprofile Public Subnet 3 in Zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ public_subnet3_cidr }}"
        az: "{{ zone3 }}"
        region: "{{ region }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_public_subnet3
      register: public_subnet3_out

    - name: Create Tecprofile Private Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ private_subnet1_cidr }}"
        az: "{{ zone1 }}"
        region: "{{ region }}"
        map_public: no
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_private_subnet1
      register: private_subnet1_out

    - name: Create Tecprofile Private Subnet 2 in Zone2 
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ private_subnet2_cidr }}"
        az: "{{ zone2 }}"
        region: "{{ region }}"
        map_public: no
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_private_subnet2
      register: private_subnet2_out

    - name: Create Tecprofile Private Subnet 3 in Zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ private_subnet3_cidr }}"
        az: "{{ zone3 }}"
        region: "{{ region }}"
        map_public: no
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_private_subnet3
      register: private_subnet3_out

    - name: Create Tecprofile Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_Internet_Gateway
      register: igw_out

    # - name: Attach Internet Gateway to VPC
    #   amazon.aws.ec2_vpc_igw:
    #     vpc_id: "{{ vpcout.vpc.id }}"
    #     internet_gateway_id: "{{ igw_out.internet_gateway.id }}"
    #     region: "{{ region }}"
    #     state: "{{ state }}"
    #   register: igw_attach_out

    - name: Create Tecprofile NAT Gateway for subnet1 due to cost and Allocate EIP
      amazon.aws.ec2_vpc_nat_gateway:
        state: "{{ state }}"
        subnet_id: "{{ public_subnet1_out.subnet.id }}"
        wait: true
        region: "{{ region }}"
        if_exist_do_not_create: true
        resource_tags:
          Name: Tecprofile_NAT_Gateway
      register: nat_out

    - name: Create Tecprofile Route Table for Private Subnet
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        resource_tags:
          Name: Tecprofile_Private_Route_Table
        subnets:
          - "{{ private_subnet1_out.subnet.id }}"
          - "{{ private_subnet2_out.subnet.id }}"
          - "{{ private_subnet3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_out.nat_gateway_id }}"
      register: private_route_table_out 

    - name: Create Tecprofile Route Table for Public Subnet
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: Tecprofile_Public_Route_Table
        subnets:
          - "{{ public_subnet1_out.subnet.id }}"
          - "{{ public_subnet2_out.subnet.id }}"
          - "{{ public_subnet3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"
      register: public_route_table_out
      
    