- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create Tecprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug: 
        var: vpcout

    - name: Create Tecprofile Public Subnet 1 in Zone1
      amazon.aws.ec2_vpc_subnet:
        public_subnet_1_name: "{{ public_subnet_1_name }}"
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ public_subnet1_cidr }}"
        az: "{{ zone1 }}"
        region: "{{ region }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: "{{ public_subnet_1_name }}"
      register: public_subnet1_out

    